name = "sbburgerweek-track"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
ACCOUNT_ID = "95bdaad9a0525e9a9af474a004504732"

[[analytics_engine_datasets]]
binding = "TRACKER"
dataset = "sbburgerweek"
